"""Strategy-driven extraction engine.

Executes declarative ExtractionStrategy JSON against raw HTML. Supports
multiple signals: CSS selectors, XPath, JSON-LD, OpenGraph metadata and
semantic HTML (<time> elements). The strategy is data — never code — so it is
safe to accept strategies generated by the healing LLM.
"""

import json
import re
from datetime import datetime
from urllib.parse import urljoin

from dateutil import parser as date_parser
from lxml import etree
from selectolax.parser import HTMLParser

from app.llm.schemas import ExtractionField, ExtractionStrategy

_DATE_PATTERNS = [
    r"\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\.?\s+\d{1,2},?\s+\d{4}",
    r"\b\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\.?\s+\d{4}",
    r"\b\d{4}-\d{2}-\d{2}(?:[T ]\d{2}:\d{2}(?::\d{2})?)?",
]

_JSONLD_TYPES = {
    "title": ["headline", "name", "title"],
    "url": ["url", "@id", "mainEntityOfPage"],
    "published_at": ["datePublished", "uploadDate"],
    "summary": ["description", "abstract"],
    "author": ["author"],
}


def _clean(text: str | None) -> str | None:
    if text is None:
        return None
    text = re.sub(r"\s+", " ", text).strip()
    return text or None


def _parse_date(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        dt = date_parser.parse(value.strip())
        return dt if dt.year >= 1990 else None
    except (ValueError, OverflowError):
        return None


class StrategyExecutor:
    """Runs an ExtractionStrategy against a page. Stateless and safe."""

    def __init__(self, html: str, base_url: str):
        self.html = html
        self.base_url = base_url
        self.tree = HTMLParser(html)
        try:
            self.lxml_tree = etree.HTML(html.encode() if isinstance(html, str) else html)
        except etree.ParserError:
            self.lxml_tree = None
        self._jsonld = self._load_jsonld()

    # -------------------------------------------------- signal methods

    def _css(self, root, field: ExtractionField) -> str | None:
        node = root.css_first(field.selector)
        if node is None:
            return None
        if field.attribute in ("text", ""):
            return _clean(node.text(separator=" ", strip=True)) if node.text() else _clean(node.text_content() if hasattr(node, "text_content") else None)
        attrs = node.attributes or {}
        value = attrs.get(field.attribute)
        return _clean(value)

    def _xpath(self, field: ExtractionField) -> str | None:
        if self.lxml_tree is None:
            return None
        results = self.lxml_tree.xpath(field.selector)
        for result in results[:5]:
            if isinstance(result, str):
                cleaned = _clean(result)
                if cleaned:
                    return cleaned
            elif hasattr(result, "text_content"):
                attr = field.attribute
                if attr not in ("text", ""):
                    value = result.get(attr)
                    cleaned = _clean(value)
                    if cleaned:
                        return cleaned
                cleaned = _clean(result.text_content())
                if cleaned:
                    return cleaned
            elif isinstance(result, etree._Element):
                cleaned = _clean(result.get(field.attribute, ""))
                if cleaned:
                    return cleaned
        return None

    def _og(self, field: ExtractionField) -> str | None:
        name = field.selector or field.path
        for meta in self.tree.css("meta"):
            props = (meta.attributes.get("property"), meta.attributes.get("name"))
            if name in props:
                return _clean(meta.attributes.get("content"))
        return None

    def _jsonld_walk(self, obj, key: str):
        """Recursively find values for `key` in nested JSON-LD structures."""
        found = []
        if isinstance(obj, dict):
            for k, v in obj.items():
                if k == key:
                    if isinstance(v, str):
                        found.append(v)
                    elif isinstance(v, dict):
                        inner = v.get("name")
                        if isinstance(inner, str):
                            found.append(inner)
                    elif isinstance(v, list) and v and isinstance(v[0], str):
                        found.append(v[0])
                found.extend(self._jsonld_walk(v, key))
        elif isinstance(obj, list):
            for item in obj:
                found.extend(self._jsonld_walk(item, key))
        return found

    def _load_jsonld(self):
        blocks = []
        for script in self.tree.css('script[type="application/ld+json"]'):
            raw = script.text()
            if not raw:
                continue
            try:
                blocks.append(json.loads(raw))
            except json.JSONDecodeError:
                continue
        return blocks

    def _from_jsonld(self, field_name: str, path: str) -> str | None:
        path = path or field_name
        keys = _JSONLD_TYPES.get(path, [path])
        for block in self._jsonld:
            for key in keys:
                values = self._jsonld_walk(block, key)
                if values:
                    return _clean(str(values[0]))
        return None

    def _semantic(self, field_name: str, root=None) -> str | None:
        tree = root if root is not None else self.tree
        for time_el in tree.css("time[datetime]"):
            dt = _parse_date(time_el.attributes.get("datetime"))
            if dt:
                return time_el.attributes["datetime"]
            text = _clean(time_el.text())
            if text:
                return text
        for time_el in tree.css("time"):
            text = _clean(time_el.text())
            if text:
                return text
        scope = root if root is not None else self.tree
        if scope is self.tree:
            body_node = scope.body
            body_text = body_node.text(separator=" ", strip=True) if body_node else ""
        else:
            body_text = scope.text(separator=" ", strip=True) or ""
        for pattern in _DATE_PATTERNS:
            match = re.search(pattern, body_text or "")
            if match:
                return match.group(0)
        return None

    # -------------------------------------------------- field resolution

    def resolve_field(self, field_name: str, field: ExtractionField, container=None) -> str | None:
        method = field.method
        if method == "css":
            root = container if container is not None else self.tree
            return self._css(root, field)
        if method == "xpath":
            return self._xpath(field)
        if method == "og":
            return self._og(field)
        if method == "jsonld":
            return self._from_jsonld(field_name, field.path)
        if method == "semantic":
            value = self._semantic(field_name, root=container)
            return _parse_date_str(value)
        return None

    def extract(self, strategy: ExtractionStrategy | dict) -> list[dict]:
        """Return a list of raw article dicts extracted per the strategy."""
        if isinstance(strategy, dict):
            from app.llm.schemas import ExtractionStrategy as _ES

            strategy = _ES.model_validate(strategy)
        items: list[dict] = []

        if strategy.list_selector is not None:
            containers = self._select_containers(strategy.list_selector)
            for container in containers[:100]:
                item = {}
                for field_name, field in strategy.fields.items():
                    item[field_name] = self.resolve_field(field_name, field, container=container)
                items.append(item)
        else:
            item = {}
            for field_name, field in strategy.fields.items():
                item[field_name] = self.resolve_field(field_name, field)
            items.append(item)

        normalized = []
        for item in items:
            title = item.get("title")
            url_raw = item.get("url") or item.get("link")
            if not title or not url_raw:
                continue
            entry = dict(item)
            entry["url"] = urljoin(self.base_url, url_raw.split("?")[0] if _is_anchor(url_raw) else url_raw)
            normalized.append(entry)
        return normalized

    def _select_containers(self, selector_obj) -> list:
        if selector_obj.method == "xpath":
            if self.lxml_tree is None:
                return []
            nodes = self.lxml_tree.xpath(selector_obj.selector)
            # re-wrap lxml elements into selectolax nodes so css field
            # selectors keep working uniformly
            wrapped = []
            for n in nodes:
                if isinstance(n, etree._Element) and not isinstance(n.tag, str):
                    continue
                if isinstance(n, etree._Element):
                    wrapped.append(HTMLParser(etree.tostring(n, encoding="unicode")))
            return wrapped
        return [n for n in self.tree.css(selector_obj.selector)]


def _parse_date_str(value: str | None) -> str | None:
    return value


def _is_anchor(url: str) -> bool:
    return url.startswith(("#", "javascript:", "mailto:", "tel:")) or not url




def extract_articles(html: str, strategy: ExtractionStrategy, base_url: str) -> list[dict]:
    return StrategyExecutor(html, base_url).extract(strategy)


def extract_rss_entries(feed_data) -> list[dict]:
    """Normalize feedparser entries into the same shape as HTML extraction."""
    entries = []
    for entry in feed_data.entries:
        published = None
        for attr in ("published_parsed", "updated_parsed"):
            parsed = getattr(entry, attr, None)
            if parsed:
                published = datetime(*parsed[:6])
                break
        image = None
        if getattr(entry, "media_content", None):
            image = entry.media_content[0].get("url")
        entries.append(
            {
                "title": _clean(getattr(entry, "title", "")),
                "url": getattr(entry, "link", ""),
                "summary": _clean(getattr(entry, "summary", "")),
                "author": _clean(getattr(entry, "author", "")),
                "published_at": published.isoformat() if published else None,
                "image_url": image,
            }
        )
    return [e for e in entries if e["title"] and e["url"]]
